controllers/CamposController.php
<?php

namespace app\controllers;

use app\models\Alquileres;
use app\models\Campos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CamposController implements the CRUD actions for Campos model.
 */
class CamposController extends GeneralController
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Campos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Campos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Campos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Campos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Campos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Campos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Campos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Campos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Campos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Campos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
            public function actionReservations($id){
        $model = Alquileres::find()->where(['idCampo' => $id])->all();
        return $this->render('List',['reservesList'=>$model]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Alquileres;
use app\models\Campos;
use app\models\Comments;
use app\models\Rates;
use app\models\Socios;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends GeneralController
{
    /**
     * {@inheritdoc}
     */

     
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $campos=Campos::find()->all();

        return $this->render('index',["campos"=>$campos]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionRegister()
{
    $model = new Socios();

    if (Yii::$app->request->isPost) {
        $postData = Yii::$app->request->post();
        
        $model->load($postData);

        if ($model->validate() && $model->save()) {
            // Registration successful, redirect to a success page or perform additional actions
            return $this->redirect(['site/success']);
        }
    }

    return $this->render('register', ['model' => $model]);
}
public function actionSuccess()
{
    return $this->render('success');
}
public function actionViewcampo($id)
{
    $campo = Campos::findOne($id);
    $comments=Comments::find()->where(['postId'=>$id])->all();
    $ratingModel = new Rates(); // Create an instance of the Rates model for the rating form

    return $this->render('campoDetails', [
        'model' => $campo,
        'ratingModel' => $ratingModel, // Pass the rating model to the view
        'comments'=>$comments,
    ]);
}

 /**
     * Creates a new Alquileres model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
public function actionReserve($id, $userid)
{
    
    if (Yii::$app->user->isGuest) {
        return $this->redirect(['site/login']);
    }
    
    $model = new Alquileres();
    $campo = Campos::findOne($id);
    $socio = Socios::findOne($userid);
    $fechas = Alquileres::find()
    ->select('fechaHora')->where(["idCampo"=>$id])
    ->asArray()
    ->column();


    
    if (!$campo || !$socio) {
        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    $model->idSocio = $socio->id;
    $model->idCampo = $campo->id;
    
    if ($this->request->isPost) {
        if ($model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['/site/reserved', 'id' => $model->id]);
        }
    } else {
        $model->loadDefaultValues();
    }

    return $this->render('reserve', [
        'model' => $model,"campo"=> $campo,"socio"=>$socio,"fechas"=>$fechas
    ]);
}
public function actionReserved($id){
$model=Alquileres::findOne($id);
return $this->render('reservationCard', ['model' => $model]);
}
public function actionMyreservations($id){
    $model=Alquileres::find()->where(["idSocio"=>$id])->all();
    return $this->render('myreservation', ['model' => $model]);
}
public function actionDelete($id)
{
    $model = Alquileres::findOne($id);

    if ($model !== null) {
        $currentTime = time();  // Current Unix timestamp
        $deleteTime = strtotime($model->fechaHora);  // Assuming 'delete_time' is a field in the Alquileres model representing the deletion time

        if (($deleteTime - $currentTime) > (24 * 60 * 60)) {
            $model->delete();
        } else {
            throw new \Exception('The item cannot be deleted as the delete time has already passed.');
        }
    } else {
        throw new NotFoundHttpException('The requested item does not exist.');
    }

    return $this->redirect(['/site/myreservations', 'id' => Yii::$app->user->id]);
}


public function actionUpdate($id)
{
    $model = Alquileres::findOne($id);
     $fechas = Alquileres::find()
    ->select('fechaHora')
    ->asArray()
    ->column();


    if ($model !== null) {
        $currentTime = time();  // Current Unix timestamp
        $updateTime = strtotime($model->fechaHora);  // Assuming 'update_time' is a field in the Alquileres model representing the update time

        if (($updateTime - $currentTime) <= (24 * 60 * 60)) {
            Yii::$app->session->setFlash('error', 'The item cannot be updated as the update time has already passed.');
            return $this->redirect(['/site/myreservations', 'id' => Yii::$app->user->id]);
        }

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['/site/myreservations', 'id' => Yii::$app->user->id]);
        }
    } else {
        throw new NotFoundHttpException('The requested item does not exist.');
    }

    return $this->render('update', [
        'model' => $model,"fechas"=>$fechas
    ]);
}
public function actionRate($id)
{
    $rateModel = new Rates();
    $rateModel->idCampo = $id;
    $rateModel->userId = Yii::$app->user->id;
   

    if (Yii::$app->request->isPost) {
        $postData = Yii::$app->request->post();

        if ($rateModel->load($postData) && $rateModel->validate()) {
            $rateModel->save();

            // Calculate and update the average rate for the corresponding campo
            $campo = Campos::findOne($id);
            $campo->rate = $campo->getAverage();
            $campo->save();
        }


        return $this->redirect(['viewcampo', 'id' => $id]);
    }

    return $this->render('rate', ['rateModel' => $rateModel,]);
}



}

controllers/SociosController.php
<?php

namespace app\controllers;

use app\models\Alquileres;
use app\models\Socios;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SociosController implements the CRUD actions for Socios model.
 */
class SociosController extends GeneralController
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Socios models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Socios::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Socios model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Socios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Socios();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Socios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Socios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Socios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Socios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Socios::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
             public function actionReservations($id){
        $model = Alquileres::find()->where(['idSocio' => $id])->all();
        return $this->render('List',['reservesList'=>$model]);
    }
}

views/layouts/_adminMenu.php
    <?php
    use yii\bootstrap5\Nav;
    use yii\helpers\Html;
    
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ['label'=>'administration','items'=>[
                   ['label' => 'Alquileres', 'url' => ['/alquileres/index']],
              ['label' => 'Campos', 'url' => ['/campos/index']],
               ['label' => 'Socios', 'url' => ['/socios/index']],
            ]],['label' => 'My Reservations', 'url' => ['/site/myreservations','id'=>Yii::$app->user->id]],
          
            Yii::$app->user->isGuest
                ? ['label' => 'Login', 'url' => ['/site/login']]
                : '<li class="nav-item">'
                    . Html::beginForm(['/site/logout'])
                    . Html::submitButton(
                        'Logout (' . Yii::$app->user->identity->nombre . ')',
                        ['class' => 'nav-link btn btn-link logout']
                    )
                    . Html::endForm()
                    . '</li>'
        ]
    ]);
    ?>
    <style>
.nav-item {
    max-height: 40px;
}
    </style>

views/layouts/_guestMenu.php
    <?php
    use yii\bootstrap5\Nav;
    use yii\helpers\Html;
    
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ['label' => 'Register', 'url' => ['/site/register']],
          
            Yii::$app->user->isGuest
                ? ['label' => 'Login', 'url' => ['/site/login']]
                : '<li class="nav-item">'
                    . Html::beginForm(['/site/logout'])
                    . Html::submitButton(
                        'Logout (' . Yii::$app->user->identity->nombre . ')',
                        ['class' => 'nav-link btn btn-link logout']
                    )
                    . Html::endForm()
                    . '</li>'
        ]
    ]);

views/layouts/_userMenu.php
    <?php
    use yii\bootstrap5\Nav;
    use yii\helpers\Html;
    
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ['label' => 'My Reservations', 'url' => ['/site/myreservations','id'=>Yii::$app->user->id]],
            
          
            Yii::$app->user->isGuest
                ? ['label' => 'Login', 'url' => ['/site/login']]
                : '<li class="nav-item">'
                    . Html::beginForm(['/site/logout'])
                    . Html::submitButton(
                        'Logout (' . Yii::$app->user->identity->nombre . ')',
                        ['class' => 'nav-link btn btn-link logout']
                    )
                    . Html::endForm()
                    . '</li>'
        ]
    ]);
?>
    <style>
.nav-item {
    max-height: 40px;
}
    </style>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap5\Breadcrumbs;
use yii\bootstrap5\Html;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;

AppAsset::register($this);

$this->registerCsrfMetaTags();
$this->registerMetaTag(['charset' => Yii::$app->charset], 'charset');
$this->registerMetaTag(['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no']);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['meta_description'] ?? '']);
$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['meta_keywords'] ?? '']);
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => Yii::getAlias('@web/favicon.ico')]);
$this->registerJsFile('https://code.jquery.com/jquery-3.6.0.min.js', ['position' => $this::POS_HEAD]);

?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">

<head>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>


</head>

<body class="d-flex flex-column h-100">
    <?php $this->beginBody() ?>

    <header id="header">
        <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => ['class' => 'navbar-expand-md navbar-dark bg-dark fixed-top']
    ]);
       if (Yii::$app->user->isGuest) {
        echo $this->render('_guestMenu');
    } elseif (Yii::$app->user->identity->isAdmin) {
        echo $this->render('_adminMenu');
    } else {
        echo $this->render('_userMenu');
    }
      
    NavBar::end();
    ?>
    </header>

    <main id="main" class="flex-shrink-0" role="main">
        <div class="container">
            <?php if (!empty($this->params['breadcrumbs'])): ?>
            <?= Breadcrumbs::widget(['links' => $this->params['breadcrumbs']]) ?>
            <?php endif ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </main>

    <footer id="footer" class="mt-auto py-3 bg-light">
        <div class="container">
            <div class="row text-muted">
                <div class="col-md-6 text-center text-md-start">&copy; My Company <?= date('Y') ?></div>
            </div>
        </div>
    </footer>

    <?php $this->endBody() ?>

</body>

</html>
<?php $this->endPage() ?>