controllers/CommentsController.php
<?php

namespace app\controllers;

use app\models\Comments;
use app\models\Replies;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentsController implements the CRUD actions for Comments model.
 */
class CommentsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Comments models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Comments::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comments model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comments model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionAdd($id)
    {
        $model = new Comments();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['/site/viewcampo', 'id' => $id]);
            }
        } else {
            $model->loadDefaultValues();
        }

     return $this->render('/site/viewcampo', ['id' => $id]);
    }

    /**
     * Updates an existing Comments model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Comments model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
public function actionDeletecomment($id,$campo)
{
    Replies::deleteAll(['commentId' => $id]);
    $this->findModel($id)->delete();

    return $this->redirect(['/site/viewcampo',"id"=>$campo]);
}


    /**
     * Finds the Comments model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Comments the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comments::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
}

controllers/RepliesController.php
<?php

namespace app\controllers;

use app\models\Comments;
use Yii;
use app\models\Replies;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RepliesController implements the CRUD actions for Replies model.
 */
class RepliesController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Replies models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Replies::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Replies model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Replies model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Replies();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
// Controller action to add a reply
public function actionAdd($id)
{
    $comment = Comments::findOne($id);

    if (!$comment) {
        throw new NotFoundHttpException('The requested comment does not exist.');
    }

    $model = new Replies();
    $model->commentId = $comment->id;
    $model->userId = Yii::$app->user->id;
    $model->timestamp = date('Y-m-d H:i:s');

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
        // Reply saved successfully
        return $this->redirect(['/site/viewcampo', 'id' => $comment->postId]); // Redirect to the comment's view page
    } else {
        // Display the reply form with errors
        return $this->render('view', [
            'comment' => $comment,
            'model' => $model,
        ]);
    }
}


    /**
     * Updates an existing Replies model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Replies model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
       public function actionDeletereply($id,$campo)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['/site/viewcampo',"id"=>$campo]);
    }

    /**
     * Finds the Replies model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Replies the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Replies::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Alquileres;
use app\models\Campos;
use app\models\Comments;
use app\models\Rates;
use app\models\Socios;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends GeneralController
{
    /**
     * {@inheritdoc}
     */

     
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $campos=Campos::find()->all();

        return $this->render('index',["campos"=>$campos]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionRegister()
{
    $model = new Socios();

    if (Yii::$app->request->isPost) {
        $postData = Yii::$app->request->post();
        
        $model->load($postData);

        if ($model->validate() && $model->save()) {
            // Registration successful, redirect to a success page or perform additional actions
            return $this->redirect(['site/success']);
        }
    }

    return $this->render('register', ['model' => $model]);
}
public function actionSuccess()
{
    return $this->render('success');
}
public function actionViewcampo($id)
{
    $campo = Campos::findOne($id);
    $comments=Comments::find()->where(['postId'=>$id])->all();
    $ratingModel = new Rates(); // Create an instance of the Rates model for the rating form

    return $this->render('campoDetails', [
        'model' => $campo,
        'ratingModel' => $ratingModel, // Pass the rating model to the view
        'comments'=>$comments,
    ]);
}

 /**
     * Creates a new Alquileres model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
public function actionReserve($id, $userid)
{
    
    if (Yii::$app->user->isGuest) {
        return $this->redirect(['site/login']);
    }
    
    $model = new Alquileres();
    $campo = Campos::findOne($id);
    $socio = Socios::findOne($userid);
    $fechas = Alquileres::find()
    ->select('fechaHora')->where(["idCampo"=>$id])
    ->asArray()
    ->column();


    
    if (!$campo || !$socio) {
        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    $model->idSocio = $socio->id;
    $model->idCampo = $campo->id;
    
    if ($this->request->isPost) {
        if ($model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['/site/reserved', 'id' => $model->id]);
        }
    } else {
        $model->loadDefaultValues();
    }

    return $this->render('reserve', [
        'model' => $model,"campo"=> $campo,"socio"=>$socio,"fechas"=>$fechas
    ]);
}
public function actionReserved($id){
$model=Alquileres::findOne($id);
return $this->render('reservationCard', ['model' => $model]);
}
public function actionMyreservations($id){
    $model=Alquileres::find()->where(["idSocio"=>$id])->all();
    return $this->render('myreservation', ['model' => $model]);
}
public function actionDelete($id)
{
    $model = Alquileres::findOne($id);

    if ($model !== null) {
        $currentTime = time();  // Current Unix timestamp
        $deleteTime = strtotime($model->fechaHora);  // Assuming 'delete_time' is a field in the Alquileres model representing the deletion time

        if (($deleteTime - $currentTime) > (24 * 60 * 60)) {
            $model->delete();
        } else {
            throw new \Exception('The item cannot be deleted as the delete time has already passed.');
        }
    } else {
        throw new NotFoundHttpException('The requested item does not exist.');
    }

    return $this->redirect(['/site/myreservations', 'id' => Yii::$app->user->id]);
}


public function actionUpdate($id)
{
    $model = Alquileres::findOne($id);
     $fechas = Alquileres::find()
    ->select('fechaHora')
    ->asArray()
    ->column();


    if ($model !== null) {
        $currentTime = time();  // Current Unix timestamp
        $updateTime = strtotime($model->fechaHora);  // Assuming 'update_time' is a field in the Alquileres model representing the update time

        if (($updateTime - $currentTime) <= (24 * 60 * 60)) {
            Yii::$app->session->setFlash('error', 'The item cannot be updated as the update time has already passed.');
            return $this->redirect(['/site/myreservations', 'id' => Yii::$app->user->id]);
        }

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['/site/myreservations', 'id' => Yii::$app->user->id]);
        }
    } else {
        throw new NotFoundHttpException('The requested item does not exist.');
    }

    return $this->render('update', [
        'model' => $model,"fechas"=>$fechas
    ]);
}
public function actionRate($id)
{
    $rateModel = new Rates();
    $rateModel->idCampo = $id;
    $rateModel->userId = Yii::$app->user->id;
   

    if (Yii::$app->request->isPost) {
        $postData = Yii::$app->request->post();

        if ($rateModel->load($postData) && $rateModel->validate()) {
            $rateModel->save();

            // Calculate and update the average rate for the corresponding campo
            $campo = Campos::findOne($id);
            $campo->rate = $campo->getAverage();
            $campo->save();
        }


        return $this->redirect(['viewcampo', 'id' => $id]);
    }

    return $this->render('rate', ['rateModel' => $rateModel,]);
}



}

views/site/_Campo.php
<?php
use kartik\rating\StarRating;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\YiiAsset;

// Register YiiAsset to include necessary JavaScript and CSS files
YiiAsset::register($this);
?>

<style>
.card-img-height {
    height: 200px;
    object-fit: cover;
}

.card {
    padding: 10px;
    position: relative;
    transition: transform 0.3s ease;
}

.card-container {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 10px;
}

.card:hover {
    transform: scale(1.05);
    z-index: 1;
}

.login-message {
    margin-top: 10px;
    font-size: 14px;
    color: red;
}
</style>

<div class="card-container">
    <div class="card">
        <img src="<?= Yii::getAlias('@web') . '/imgs/campos/' . $model->foto ?>" class="card-img-top card-img-height"
            alt="Campo Image">
        <div class="card-body">
            <h5 class="card-title"><?= $model->nombre ?></h5>
            <p><?= $model->direccion ?></p>
            <?php
                       echo StarRating::widget([
    'name' => 'rating_35',
    'value' => $model->average,
    'pluginOptions' => ['displayOnly' => true,"size"=>'sm']
]);
?>
        </div>
        <div class="card-footer">
            <?php if (Yii::$app->user->isGuest) : ?>
            <?= Html::a('View Details', ['viewcampo', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Reservar Ahora', ['site/login'], ['class' => 'btn btn-danger']) ?>
            <?php else : ?>
            <?= Html::a('View Details', ['viewcampo', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Reservar Ahora',
             ['reserve', 'id' => $model->id, 'userid' => Yii::$app->user->id], ['class' => 'btn btn-danger']) ?>
            <?php endif; ?>
        </div>
    </div>
</div>

views/site/_formReserve.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;
use kartik\date\DatePicker;

/** @var yii\widgets\ActiveForm $form */
/** @var array $fechas */
?>

<div class="Reservation">
    <?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'idSocio')->dropDownList([$socio->id => $socio->nombre],
     ['readonly' => true]) ?>

    <?= $form->field($model, 'idCampo')->dropDownList([$campo->id => $campo->nombre],
     ['readonly' => true]) ?>

    <?= $form->field($model, 'fechaHora')->textInput([
    'readonly' => true,
    'maxlength' => 13,
    'placeholder' => 'fecha hora',
]) ?>


    <div id="fecha">
        <label for="check_issue_date">Fecha</label>
        <?= 
    DatePicker::widget([
        'name' => 'check_issue_date', 
        'options' => ['placeholder' => 'Select issue date ...', 'readonly' => true],
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true,
            'startDate' => "+0d",
            'endDate' => "+7d",
            'autoclose' => true,
        ]
    ]);
    ?>
    </div>
    <br>
    <div id="fecha_hora_container" class="d-none">
        <?php
echo DateTimePicker::widget([
    'name' => 'check_hora',
    'options' => ['id' => 'fecha_hora', 'placeholder' => 'Select date and time...', 'readonly' => true],
    'readonly' => true,
    'pluginOptions' => [
        'format' => 'hh',
        'autoclose' => true,
        'minView' => 1,
        'maxView' => 0,
        'startView' => 1,
        'hoursDisabled' => '0,1,2,3,4,5,6,7,8,9,22,23',
        //'showMeridian' => true,
    ],
]);
?>
    </div>



    <?= $form->field($model, 'horas')->dropDownList(["1" => 1, "2" => 2], ['id' => 'horas-field']) ?>

    <?= $form->field($model, 'personas')->textInput(['readonly' => true, 'value' => $campo->aforo]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
<?php include('styles/reservationConfirem.php'); ?>

views/site/_formUpdateReserve.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;
use kartik\date\DatePicker;

/** @var yii\widgets\ActiveForm $form */
/** @var array $fechas */
?>


<div class="Reservation">
    <?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'idSocio')->dropDownList([$model->idSocio0->id => $model->idSocio0->nombre ],
     ['readonly' => true]) ?>

    <?= $form->field($model, 'idCampo')->dropDownList([$model->idCampo0->id => $model->idCampo0->nombre],
     ['readonly' => true]) ?>

    <?= $form->field($model, 'fechaHora')->textInput([
    'readonly' => true,
    'maxlength' => 13,
    'placeholder' => 'fecha hora',
]) ?>

    <div id="fecha">
        <label for="check_issue_date">Fecha</label>
        <?= 
    DatePicker::widget([
        'name' => 'check_issue_date', 
        'options' => ['placeholder' => 'Select issue date ...', 'readonly' => true],
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true,
            'startDate' => "+0d",
            'endDate' => "+7d",
            'autoclose' => true,
        ]
    ]);
    ?>
    </div>
    <br>
    <div id="fecha_hora_container" class="d-none">
        <?php
echo DateTimePicker::widget([
    'name' => 'check_hora',
    'options' => ['id' => 'fecha_hora', 'placeholder' => 'Select date and time...', 'readonly' => true],
    'readonly' => true,
    'pluginOptions' => [
        'format' => 'hh',
        'todayHighlight' => true,
        'autoclose' => true,
        'minView' => 1,
        'maxView' => 0,
        'startView' => 1,
        'hoursDisabled' => '0,1,2,3,4,5,6,7,8,9,22,23',
    ],
]);
?>
    </div>



    <?= $form->field($model, 'horas')->dropDownList(["1" => 1, "2" => 2], ['id' => 'horas-field']) ?>

    <?= $form->field($model, 'personas')->textInput(['readonly' => true, 'value' => $model->idCampo0->aforo]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
<?php include('styles/reservationConfirem.php'); ?>

views/site/campoDetails.php
<?php
use app\models\Comments;
use app\models\Replies;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = $model->nombre;
?>

<div class="campo-view">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-6">
            <?= Html::img(Url::to(['imgs/campos/' . $model->foto]), ['class' => 'campo-image']) ?>
        </div>
        <div class="col-lg-6">
            <div class="campo-details">
                <p><strong>Aforo:</strong> <?= Html::encode($model->aforo) ?></p>
                <p><strong>Precio por hora:</strong> <?= Html::encode($model->precio) ?></p>
                <p><strong>Dirección:</strong>
                    <?= Html::a(Html::encode($model->direccion), '#', ['target' => '_blank']) ?></p>
                <p><strong>Teléfono:</strong> <?= Html::encode($model->telefono) ?></p>
                <p><strong>Tipo:</strong> <?= Html::encode($model->tipo) ?></p>

                <?= Html::a('Reservar Ahora', ['reserve', 'id' => $model->id, 'userid' => Yii::$app->user->id], ['class' => 'btn btn-danger']) ?>

            </div>
        </div>
    </div>

    <div class="modal" id="ratingModal" tabindex="-1" role="dialog" aria-labelledby="ratingModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ratingModalLabel">Rate this campo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <?php $form = ActiveForm::begin(['action' => ['site/rate', 'id' => $model->id]]); ?>

                    <?= $form->field($ratingModel, 'rate')->widget(\kartik\rating\StarRating::class, [
                                'name' => 'rating_21',
                                'pluginOptions' => [
                                    'min' => 0,
                                    'max' => 5,
                                    'step' => 1,
                                    'size' => 'lg',
                                    'starCaptions' => [
                                        1 => 'Very Bad',
                                        2 => 'Bad',
                                        3 => 'Average',
                                        4 => 'Good',
                                        5 => 'Excellent',
                                    ],
                                    'starCaptionClasses' => [
                                        1 => 'text-danger',
                                        2 => 'text-warning',
                                        3 => 'text-info',
                                        4 => 'text-primary',
                                        5 => 'text-success',
                                    ],
                                ],
                            ])->label('Rate this campo') ?>

                    <?= $form->field($ratingModel, 'comment')->textarea(['rows' => 3])->label('Comment') ?>

                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
    <?php include('rateScript/RatingDetails.php') ?>

    <div class="comments-section">
        <div class="comment-form">
            <?php $newComment = new Comments(); ?>
            <?php $form = ActiveForm::begin(['action' => ['comments/add', 'id' => $model->id]]); ?>

            <?= $form->field($newComment, 'comment')->textarea(['rows' => 4, 'placeholder' => 'Add your comment'])->label(false) ?>
            <?= $form->field($newComment, 'userId')->hiddenInput(['value' => Yii::$app->user->id])->label(false) ?>
            <?= $form->field($newComment, 'postId')->hiddenInput(['value' => $model->id])->label(false) ?>

            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>

            <?php ActiveForm::end(); ?>
        </div>

        <?php if (empty($comments)): ?>
        <p>No comments yet. Be the first to comment!</p>
        <?php endif; ?>

        <?php foreach ($comments as $comment): ?>
        <div class="comment">
            <div class="comment-header">
                <p class="comment-author"><?= Html::encode($comment->user->nombre) ?></p>
                <div class="comment-actions">
                    <?php if ($comment->userId === Yii::$app->user->id): ?>
                    <i class="fas fa-ellipsis-v comment-menu"></i>
                    <div class="comment-menu-options">
                        <?= Html::a('Delete', ['/comments/deletecomment', 'id' => $comment->id, 'campo' => $model->id], [
                            'class' => 'comment-menu-option delete-comment',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this comment?',
                                'method' => 'post',
                            ],
                        ]) ?>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <p class="comment-content"><?= Html::encode($comment->comment) ?></p>
            <p class="comment-actions">
                <?php foreach ($comment->likes as $like): ?>
                <span class="like-comment">Like (<?= Html::encode($like->user->nombre) ?>)</span>
                <?php endforeach; ?>
                <span class="reply-comment">Reply</span>
            </p>

            <div id="reply-container" class="reply-form" style="display: none;">
                <?php $newReply = new Replies(); ?>
                <?php $form = ActiveForm::begin(['action' => ['replies/add', 'id' => $comment->id]]); ?>

                <?= $form->field($newReply, 'replyText')->textarea(['rows' => 2, 'placeholder' => 'Add your reply'])->label(false) ?>
                <?= $form->field($newReply, 'userId')->hiddenInput(['value' => Yii::$app->user->id])->label(false) ?>
                <?= $form->field($newReply, 'commentId')->hiddenInput(['value' => $comment->id])->label(false) ?>

                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>

                <?php ActiveForm::end(); ?>
            </div>

            <?php foreach ($comment->replies as $reply): ?>
            <div class="reply">
                <div class="reply-header">
                    <p class="reply-author"><?= Html::encode($reply->user->nombre) ?></p>
                    <div class="reply-actions">
                        <?php if ($reply->userId === Yii::$app->user->id): ?>
                        <i class="fas fa-ellipsis-v reply-menu"></i>
                        <div class="reply-menu-options">
                            <?= Html::a('Delete', ['/replies/deletereply', 'id' => $reply->id, 'campo' => $model->id], [
                                    'class' => 'reply-menu-option delete-reply',
                                    'data' => [
                                        'confirm' => 'Are you sure you want to delete this reply?',
                                        'method' => 'post',
                                    ],
                                ]) ?>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="reply-bubble">
                    <p class="reply-content"><?= Html::encode($reply->replyText) ?></p>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<?php include('styles/CampoDetails.php') ?>