models/Campos.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\FileHelper;
use yii\helpers\Url;
use yii\web\UploadedFile;

/**
 * This is the model class for table "campos".
 *
 * @property int $id
 * @property string|null $nombre
 * @property int|null $aforo
 * @property float|null $precio
 * @property string|null $direccion
 * @property string|null $telefono
 * @property string|null $tipo
 * @property string|null $foto
 * @property float|null $rate
 *
 * @property Alquileres[] $alquileres
 */
class Campos extends ActiveRecord
{
    /**
     * Define a property to hold the uploaded file.
     * This is not a database field.
     *
     * @var UploadedFile
     */
    public $archivo;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'campos';
    }

    /**
     * {@inheritdoc}
     */
public function rules()
{
    return [
        [['id'], 'required'],
        [['id', 'aforo'], 'integer'],
        [['precio'], 'number'],
        [['nombre'], 'string', 'max' => 300],
        [['direccion'], 'string', 'max' => 400],
        [['telefono'], 'string', 'max' => 20],
        [['tipo'], 'string', 'max' => 200],
        [['archivo'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, webp'],
        [['rate'], 'default', 'value' => 0],
    ];
}
/**
 * Calculate the average rate based on the data in the `rates` table.
 *
 * @return float|null The average rate or null if there are no rates available.
 */


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'aforo' => 'Aforo',
            'precio' => 'Precio',
            'direccion' => 'Dirección',
            'telefono' => 'Teléfono',
            'tipo' => 'Tipo',
            'foto' => 'Foto',
        ];
    }

    /**
     * Gets query for [[Alquileres]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAlquileres()
    {
        return $this->hasMany(Alquileres::class, ['idCampo' => 'id']);
    }
    
    public function getVotes()
    {
        return $this->hasMany(Rates::class, ['idCampo' => 'id']);
    }
 public function getAverage()
    {
          // Retrieve the sum of the 'rate' column for rows matching the condition
    $totalRate = (float) Rates::find()->where(['idCampo' => $this->id])->sum('rate');
    
    // Retrieve the count of rows matching the condition
    $rowCount = (int) Rates::find()->where(['idCampo' => $this->id])->count();

    if ($rowCount > 0) {
        // Calculate the average rate and round it to 1 decimal place
        $averageRate = round($totalRate / $rowCount, 1);

        return $averageRate;
    }
    }

    /**
     * Save the uploaded photo file to the server and store the file path in the 'foto' attribute.
     *
     * @return bool whether the photo file was saved successfully
     */
   public function subirArchivo(): bool
    {
        $this->archivo->saveAs('imgs/campos/' . $this->id . $this->archivo->name);
        return true;
    }
       public function beforeValidate()
    {
        // si he seleccionado un archivo en el formulario
        if (isset($this->archivo)) {
            $this->archivo = UploadedFile::getInstance($this, 'archivo');
        }

        return true;
    }
        public function afterValidate()
    {
        // compruebo si he seleccionado un archivo en el formulario
        if (isset($this->archivo)) {
            $this->subirArchivo();
            $this->foto = $this->id . $this->archivo->name;
        }

        return true;
    }
       /**
     * metodo que se ejecuta despues de guardar el registro 
     * en la bbdd
     * 
     * @param mixed $insert este argumento es true si estas insertando un registro y false si es una actualizacion
     * @param array $atributosAnteriores tengo todos los datos de la tabla antes de actualizar
     * @return void
     */
    public function afterSave($insert, $atributosAnteriores)
    {
        // pregunto si es una actualizacion
        if (!$insert) {
            // pregunto si he seleccionado un archivo en el formulario
            if (isset($this->archivo)) {
                // compruebo si existia foto anteriormente en la noticia
                if (isset($atributosAnteriores["foto"])) {
                    // elimino la imagen vieja del servidor
                    unlink('imgs/campos/' . $atributosAnteriores["foto"]);
                }
            }
        }
    }
public function afterDelete()
{
    // Check if the file exists before attempting to delete it
    $filePath = 'imgs/campos/' . $this->foto;
    if (!$this->foto=="") {
        unlink($filePath);
    }
    
    return parent::afterDelete();
}

    /**
     * 
     *
     * @return \yii\db\ActiveQuery
     */

}

controllers/CamposController.php
<?php

namespace app\controllers;

use app\models\Alquileres;
use app\models\Campos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CamposController implements the CRUD actions for Campos model.
 */
class CamposController extends GeneralController
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Campos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Campos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Campos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Campos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Campos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Campos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Campos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Campos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Campos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Campos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
            public function actionReservations($id){
        $model = Alquileres::find()->where(['idCampo' => $id])->all();
        return $this->render('List',['reservesList'=>$model]);
    }
}

views/Campos/List.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var array $reservesList */

$this->title = 'Reservations List';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="list-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => new \yii\data\ArrayDataProvider([
            'allModels' => $reservesList,
            'pagination' => false, // Disable pagination if needed
        ]),
        'columns' => [
            'id',
            [
            'attribute' => 'idSocio',
            'value' => function ($model) {
                return $model->idSocio0->nombre." ".$model->idSocio0->apellidos;
            },
        ], 
            'fechaHora',
            'horas',
            'personas',
            'precioTotal',
            // Add more columns as needed
        ],
    ]); ?>

</div>

views/Campos/_formCreate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/** @var yii\web\View $this */
/** @var app\models\Campos $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="campos-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'aforo')->textInput() ?>

    <?= $form->field($model, 'precio')->textInput() ?>

    <?= $form->field($model, 'direccion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'telefono')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'archivo')->widget(FileInput::class, [
        'name' => 'attachment_53',
        'pluginOptions' => [
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="fas fa-camera"></i> ',
            'browseLabel' =>  'Select Photo'
        ],
        'options' => ['accept' => 'image/*']
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/Campos/_formUpdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/** @var yii\web\View $this */
/** @var app\models\Campos $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="campos-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'aforo')->textInput() ?>

    <?= $form->field($model, 'precio')->textInput() ?>

    <?= $form->field($model, 'direccion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'telefono')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipo')->textInput(['maxlength' => true]) ?>


    <?= 
     $form->field($model, 'archivo')->widget(FileInput::class, [
    'name' => 'attachment_53',
    'pluginOptions' => [
        'showCaption' => false,
        'showRemove' => false,
        'showUpload' => false,
        'browseClass' => 'btn btn-primary btn-block',
        'browseIcon' => '<i class="fas fa-camera"></i> ',
        'browseLabel' =>  'Select Photo',
        'initialPreview' => [
            Html::img('@web/imgs/campos/'.$model->foto, ['class' => 'file-preview-image', 'alt' => 'nophoto']),
        ],
        'initialPreviewConfig' => [
            [
                'caption' => $model->foto, // File name
                'size' => file_exists(Yii::getAlias('@web/imgs/campos/'.$model->foto)) ? filesize(Yii::getAlias('@web/imgs/campos/'.$model->foto)) : 1,
            ],
        ],
    ],
    'options' => [
        'accept' => 'image/*',
    ]
]) ?>

    <?php
$file = Yii::getAlias('@web/imgs/campos/'.$model->foto);
echo "File path: " . $file;
?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/Campos/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Campos $model */

$this->title = 'Create Campos';
$this->params['breadcrumbs'][] = ['label' => 'Campos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="campos-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formCreate', [
        'model' => $model,
    ]) ?>

</div>

views/Campos/index.php
<?php

use app\models\Campos;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Campos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="campos-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Campos', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'aforo',
            'precio',
            'direccion',
            //'telefono',
            //'tipo',
              [
            'label' => 'Reservations List', // Add the label for the column
            'format' => 'raw',
            'value' => function ($model) {
                return Html::a('Reservations List', ['/campos/reservations', 'id' => $model->id], ['class' => '']);
            },
        ],
              [
                'attribute' => 'foto',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::img('@web/imgs/campos/' . $model->foto, ['class' => 'col-lg-2']);
                }
            ],
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Campos $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/Campos/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Campos $model */

$this->title = 'Update Campos: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Campos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="campos-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formUpdate', [
        'model' => $model,
    ]) ?>

</div>

views/Campos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Campos $model */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Campos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="campos-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'aforo',
            'precio',
            'direccion',
            'telefono',
            'tipo',
            'foto',
        ],
    ]) ?>

</div>